BOOTLOADER = caterina
MCU = atmega32u4
# CONVERT_TO_PROTON_C = yes

# VIA_ENABLE = yes
# LTO_ENABLE = yes
# MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
BACKLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
